AWSTemplateFormatVersion: '2010-09-09'
Description: AWS DataBrew resources

Parameters:
  BucketName:
    Type: String
  RoleArn:
    Type: String
  RecipeName:
    Type: String
  DatasetName:
    Type: String
  ProjectName:
    Type: String
  JobName:
    Type: String

Resources:

  DataBrewDataset:
    Type: AWS::DataBrew::Dataset
    Properties:
      Name: !Ref DatasetName
      Input:
        S3InputDefinition:
          Bucket: !Ref BucketName
          Key: data/sample.json

  DataBrewRecipe:
    Type: AWS::DataBrew::Recipe
    Properties:
      Name: !Ref RecipeName
      Steps: []

  DataBrewProject:
    Type: AWS::DataBrew::Project
    Properties:
      Name: !Ref ProjectName
      DatasetName: !Ref DatasetName
      RecipeName: !Ref RecipeName
      RoleArn: !Ref RoleArn

  DataBrewJob:
    Type: AWS::DataBrew::Job
    DependsOn: DataBrewProject
    Properties:
      Name: !Ref JobName
      Type: RECIPE
      RoleArn: !Ref RoleArn
      ProjectName: !Ref ProjectName
      Outputs:
      - Location:
            Bucket: !Ref BucketName
            Key: data/output/
          Format: JSON
